#!/bin/zsh
# 태스크 완료 후 PR 자동 생성
# 사용법:
#   zsh .claude/scripts/create-pr.sh <task_id> <branch>
#   zsh .claude/scripts/create-pr.sh be-adapter-arch-001 feat/be/adapter-arch
set -uo pipefail

QUEUE_FILE="${QUEUE_FILE:-docs/10-operations/tasks/task-queue.yaml}"
CMD="./.claude/scripts/task_queue.rb"

TASK_ID="${1:?task_id 필요}"
BRANCH="${2:-}"

# 브랜치 미지정 시 task_id로 자동 생성
if [[ -z "$BRANCH" ]]; then
  ROLE="$(  "$CMD" "$QUEUE_FILE" field "$TASK_ID" "role"   2>/dev/null || echo "task")"
  SHORT_ROLE="${ROLE%%\-*}"   # product-owner → product
  case "$SHORT_ROLE" in
    product)   PREFIX="feat/po" ;;
    backend)   PREFIX="feat/be" ;;
    frontend)  PREFIX="feat/fe" ;;
    reviewer)  PREFIX="ops"     ;;
    *)         PREFIX="feat"    ;;
  esac
  BRANCH="${PREFIX}/${TASK_ID}"
fi

TITLE="$("$CMD" "$QUEUE_FILE" field "$TASK_ID" "title" 2>/dev/null || echo "$TASK_ID")"
ROLE="$( "$CMD" "$QUEUE_FILE" field "$TASK_ID" "role"  2>/dev/null || echo "unknown")"
AGENT="$("$CMD" "$QUEUE_FILE" field "$TASK_ID" "agent" 2>/dev/null || echo "unknown")"

# 태스크가 소유한 산출물만 staging 대상으로 사용한다.
ARTIFACTS=("${(@f)$("$CMD" "$QUEUE_FILE" field "$TASK_ID" "artifact_paths" 2>/dev/null)}")
CHANGED="$(printf '%s\n' "${ARTIFACTS[@]}" | head -10)"

# 브랜치를 준비한다.
CURRENT_BRANCH="$(git branch --show-current)"
if ! git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git checkout -b "$BRANCH"
elif [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
  if [[ -n "$(git status --porcelain)" ]]; then
    echo "dirty worktree에서는 브랜치를 전환하지 않습니다" >&2
    exit 1
  fi
  git checkout "$BRANCH"
fi

# 신규 브랜치와 기존 브랜치 모두 태스크 산출물만 커밋한다.
for artifact in "${ARTIFACTS[@]}"; do
  [[ -z "$artifact" || "$artifact" == "null" ]] && continue
  git add -- "$artifact"
done
if ! git diff --cached --quiet; then
  git commit -m "feat($TASK_ID): complete task — $TITLE"
fi
git push -u origin "$BRANCH"

# PR 생성
gh pr create \
  --title "$TITLE" \
  --base main \
  --head "$BRANCH" \
  --body "$(cat <<EOF
## Task
- **ID:** \`$TASK_ID\`
- **Role:** $ROLE
- **Agent:** $AGENT

## 변경 파일
\`\`\`
$CHANGED
\`\`\`

## Done Criteria
$(  "$CMD" "$QUEUE_FILE" field "$TASK_ID" "done_criteria" 2>/dev/null \
    | sed 's/^/- /' || echo "- see briefing" )

## 리뷰 체크리스트
- [ ] done_criteria 항목 충족 확인
- [ ] locked_files 범위 외 수정 없음
- [ ] decision-log 기록 완료
- [ ] 다음 태스크 의존성 문제 없음

🤖 Generated by plshare2 multi-agent orchestrator
EOF
  )"
echo "PR 생성 완료: $BRANCH → main"
