#!/bin/zsh
# 태스크 완료 후 PR 자동 생성
# 사용법:
#   zsh .claude/scripts/create-pr.sh <task_id> <branch>
#   zsh .claude/scripts/create-pr.sh be-adapter-arch-001 feat/be/adapter-arch
set -uo pipefail

QUEUE_FILE="${QUEUE_FILE:-docs/10-operations/tasks/task-queue.yaml}"
CMD="./.claude/scripts/task_queue.rb"

TASK_ID="${1:?task_id 필요}"
BRANCH="${2:-}"

# 브랜치 미지정 시 task_id로 자동 생성
if [[ -z "$BRANCH" ]]; then
  ROLE="$(  "$CMD" "$QUEUE_FILE" field "$TASK_ID" "role"   2>/dev/null || echo "task")"
  SHORT_ROLE="${ROLE%%\-*}"   # product-owner → product
  case "$SHORT_ROLE" in
    product)   PREFIX="feat/po" ;;
    backend)   PREFIX="feat/be" ;;
    frontend)  PREFIX="feat/fe" ;;
    reviewer)  PREFIX="ops"     ;;
    *)         PREFIX="feat"    ;;
  esac
  BRANCH="${PREFIX}/${TASK_ID}"
fi

TITLE="$("$CMD" "$QUEUE_FILE" field "$TASK_ID" "title" 2>/dev/null || echo "$TASK_ID")"
ROLE="$( "$CMD" "$QUEUE_FILE" field "$TASK_ID" "role"  2>/dev/null || echo "unknown")"
AGENT="$("$CMD" "$QUEUE_FILE" field "$TASK_ID" "agent" 2>/dev/null || echo "unknown")"

# 현재 브랜치에서 변경된 파일 목록
CHANGED="$(git diff --name-only main...HEAD 2>/dev/null | head -10 || true)"

# 브랜치가 없으면 생성 후 현재 변경사항 커밋
CURRENT_BRANCH="$(git branch --show-current)"
if ! git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git checkout -b "$BRANCH"
  git add -A
  git commit -m "feat($TASK_ID): complete task — $TITLE" 2>/dev/null || true
  git push -u origin "$BRANCH" 2>/dev/null || true
elif [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
  git checkout "$BRANCH"
fi

# PR 생성
gh pr create \
  --title "$TITLE" \
  --base main \
  --head "$BRANCH" \
  --body "$(cat <<EOF
## Task
- **ID:** \`$TASK_ID\`
- **Role:** $ROLE
- **Agent:** $AGENT

## 변경 파일
\`\`\`
$CHANGED
\`\`\`

## Done Criteria
$(  "$CMD" "$QUEUE_FILE" field "$TASK_ID" "done_criteria" 2>/dev/null \
    | sed 's/^/- /' || echo "- see briefing" )

## 리뷰 체크리스트
- [ ] done_criteria 항목 충족 확인
- [ ] locked_files 범위 외 수정 없음
- [ ] decision-log 기록 완료
- [ ] 다음 태스크 의존성 문제 없음

🤖 Generated by plshare2 multi-agent orchestrator
EOF
  )" 2>&1 && echo "PR 생성 완료: $BRANCH → main" || echo "PR 생성 실패 또는 이미 존재"
